export interface OfficeHours {
  weekDay: string;
  date: string;
  start: string;
  end: string;
  remark: string;
}

export const OFFICE_HOURS: Array<OfficeHours> = [
  {
    weekDay: 'Freitag',
    date: '01/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Samstag',
    date: '02/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Sonntag',
    date: '03/03/24',
    start: '17:00',
    end: '20:00',
    remark: '-',
  },
  {
    weekDay: 'Montag',
    date: '04/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Dienstag',
    date: '05/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Mittwoch',
    date: '06/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Donnerstag',
    date: '07/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Freitag',
    date: '08/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Samstag',
    date: '09/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Sonntag',
    date: '10/03/24',
    start: '17:00',
    end: '20:00',
    remark: '-',
  },
  {
    weekDay: 'Montag',
    date: '11/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Dienstag',
    date: '12/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Mittwoch',
    date: '13/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Donnerstag',
    date: '14/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Freitag',
    date: '15/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Samstag',
    date: '16/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Sonntag',
    date: '17/03/24',
    start: '17:00',
    end: '20:00',
    remark: '-',
  },
  {
    weekDay: 'Montag',
    date: '18/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Dienstag',
    date: '19/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Mittwoch',
    date: '20/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Donnerstag',
    date: '21/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Freitag',
    date: '22/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Samstag',
    date: '23/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Sonntag',
    date: '24/03/24',
    start: '17:00',
    end: '20:00',
    remark: '-',
  },
  {
    weekDay: 'Montag',
    date: '25/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Dienstag',
    date: '26/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Mittwoch',
    date: '27/03/24',
    start: '-',
    end: '-',
    remark: 'nach Absprache ab 18:00 Uhr',
  },
  {
    weekDay: 'Donnerstag',
    date: '28/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Freitag',
    date: '29/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Samstag',
    date: '30/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
  {
    weekDay: 'Sonntag',
    date: '31/03/24',
    start: '-',
    end: '-',
    remark: 'frei',
  },
]


